#!/usr/bin/env bash
# GIT_RECENT_COMMITTERS_DAYS is the environment variable
N=${GIT_RECENT_COMMITTERS_DAYS:-7}  # default value for N is 7

# extract arg -n if there is one 
while [ "$#" -gt 0 ]; do
    case "$1" in
        -n)
            shift
            N="$1"
            ;;
        *)
            echo "error $1 not found"
            exit 1
            ;;
    esac
    shift
done

# check N
if ! [[ "$N" =~ ^[0-9]+$ ]] || [ "$N" -lt 0 ]; then
    echo "N can't have a negative value" >&2
    exit 1
fi

# Check if in a Git repository
git rev-parse --is-inside-work-tree > /dev/null 2>&1 || { echo "you are not in a repository"; exit 1; }

# Print results- commits in the last N days
git log --since="$N days ago" --pretty="%an" | sort | uniq -c | while read count name t; do
    echo "$name: $count commits "$t""
done

